version: "3"
services: 
  bot:
    image: "node:current-alpine"
    ports: 
      - '3001:3001'
    volumes: 
      - /var/bot/chrodman
    command: 
      - yum install git yarn
      - git clone https://github.com/akari0624/ChordMan.git
      - cd ChordMan
      - yarn install
      - npm install forever -g
      - forever start -c "yarn run start" ./